on:
  push:

jobs:
  prepare-output:
    runs-on: "ubuntu-latest"
    outputs:
      release-version: ${{ steps.create-output.outputs.release-version }}
      jar-version: ${{ steps.create-output.outputs.jar-version }}
    steps:
      - id: create-output
        env:
          version: "v0.1.3"
          parsed-version: $(echo "v0.1.3" | sed "s/^.\(.*\)/\1/")
        run: |
          echo "RELEASE-VERSION=${{ env.version }}" >> "$GITHUB_OUTPUT"
          echo "JAR-VERSION=${{ env.parsed-version }}" >> "$GITHUB_OUTPUT"
  print-output:
    runs-on: "ubuntu-latest"
    needs: prepare-output
    steps:
      - name: print-output
        run: |
          echo "Release version is: ${{needs.prepare-output.outputs.release-version}}"
          echo "Release version is: ${{needs.prepare-output.outputs.jar-version}}"
